# IO
# Do not add trailing "/", e.g. "SAMPLE_FOLDER/". Instead, use "SAMPLE_FOLDER" just.
SAMPLES: "SAMPLES"
RESULTS: "RESULTS"

# DATABASES

# for viralFlye
HMM: "databases/Pfam-A.hmm.gz"

BLASTDB_ENVIRON_VARIABLE: "/home/viller/clinical-genomics/pandemic-preparedness/snakemake_pipe/reference/blast_db/"
BLASTN_DB: "/home/viller/clinical-genomics/pandemic-preparedness/snakemake_pipe/reference/blast_db/ref_viruses_rep_genomes"
TBE_REF: "databases/fasta/TBE.fasta"
LANGAT_REF: "databases/fasta/LANGAT.fasta"


# Parameters
THREADS: 40
COVERAGE_THRESHOLD: 0
GENOME_SIZE: 10000

